"""All ORM models in one import surface.

Also exposes ``ALL_MODELS`` so migrations, seeds and tests can import the complete
metadata graph without listing modules twice.
"""

from drillai.db.base import Base
from drillai.db.models.ai import (
    AGENT_RUN_STATUSES,
    KNOWLEDGE_SOURCE_KINDS,
    LLM_OPERATIONS,
    MESSAGE_ROLES,
    TOOL_CALL_STATUSES,
    AgentRun,
    Conversation,
    Feedback,
    KnowledgeSource,
    LlmCall,
    MemoryNote,
    Message,
    PromptTemplate,
    ToolCall,
)
from drillai.db.models.asset import (
    DATUMS,
    SECTION_KINDS,
    SURVEY_SOURCES,
    TRAJECTORY_KINDS,
    WELL_STATUSES,
    WELL_TYPES,
    WELLBORE_PURPOSES,
    Field,
    Formation,
    Project,
    Rig,
    Trajectory,
    TrajectoryStation,
    Well,
    Wellbore,
    WellFormationMarker,
    WellSection,
)
from drillai.db.models.design import (
    ARTIFACT_KINDS,
    ARTIFACT_STATES,
    Artifact,
    ArtifactVersion,
    Lesson,
    Requirement,
    Risk,
    Standard,
    ValidationFinding,
)
from drillai.db.models.documents import (
    DOC_STATUSES,
    DOC_TYPES,
    EVIDENCE_KINDS,
    EXTRACTION_METHODS,
    INGESTION_JOB_STATUSES,
    RECORD_TYPES,
    REGION_KINDS,
    VALIDATION_STATES,
    Derivation,
    Document,
    DocumentChunk,
    DocumentPage,
    DocumentRegion,
    EvidenceLink,
    ExtractedRecord,
    IngestionJob,
    RawArtifact,
)
from drillai.db.models.engines import (
    ACTION_LEVELS,
    RECOMMENDATION_STATUSES,
    EngineRun,
    OffsetCandidate,
    Recommendation,
)
from drillai.db.models.equipment import (
    ITEM_CATEGORIES,
    READINESS_DIMENSIONS,
    READINESS_STATUSES,
    SERVICE_CATEGORIES,
    BomRequirement,
    CatalogItem,
    Certification,
    EquipmentUnit,
    InventoryItem,
    ReadinessAssessment,
    ReadinessItem,
    Service,
    ServiceCompany,
)
from drillai.db.models.identity import SYSTEM_ROLES, ApiToken, Membership, Organization, Role, User
from drillai.db.models.operations import (
    CAUSE_BASES,
    CLASSIFICATION_SOURCES,
    EVENT_KINDS,
    EVENT_SEVERITIES,
    EVENT_STATUSES,
    NPT_CATEGORIES,
    OPERATION_CLASSES,
    OPERATION_KINDS,
    OPERATION_PHASES,
    OPERATION_STATUSES,
    SOURCE_KINDS,
    Alert,
    Event,
    NptCode,
    Operation,
    TimeSeries,
    TimeSeriesPoint,
)
from drillai.db.models.optimization import (
    OPTIMIZATION_PROBLEMS,
    SCENARIO_STATUSES,
    CandidateSolution,
    ImpactAnalysis,
    OptimizationRun,
    Scenario,
    ScenarioChange,
    ScenarioResult,
)
from drillai.db.models.platform import (
    CONNECTOR_PROVIDERS,
    POLICY_EFFECTS,
    REGISTRY_KINDS,
    REGISTRY_STATUSES,
    RESOURCE_KINDS,
    SPAN_KINDS,
    SPAN_OPERATIONS,
    TRACE_KINDS,
    AuditLog,
    Connector,
    ConnectorEvent,
    EvaluationCase,
    EvaluationRun,
    EvaluationSuite,
    IdempotencyKey,
    MetricPoint,
    OutboundMessage,
    PolicyBinding,
    RegistryItem,
    RegistryItemVersion,
    Schedule,
    SecretRef,
    Span,
    Trace,
)
from drillai.db.models.twin import ASPECTS, STATE_KINDS, ChangeRecord, TwinAspect, TwinSnapshot
from drillai.db.models.workflow import (
    APPROVAL_KINDS,
    APPROVAL_STATUSES,
    NODE_RUN_STATUSES,
    RUN_EVENT_TYPES,
    RUN_STATUSES,
    WORKFLOW_STATUSES,
    ApprovalRequest,
    NodeRun,
    RunArtifact,
    RunEvent,
    Workflow,
    WorkflowRun,
    WorkflowVersion,
)

ALL_MODELS = [
    # identity & tenancy
    Organization, User, Role, Membership, ApiToken,
    # assets & well physical description
    Project, Field, Rig, Well, Wellbore, Formation, WellFormationMarker, WellSection,
    Trajectory, TrajectoryStation,
    # engineering artefacts & assurance
    Artifact, ArtifactVersion, Requirement, Standard, Risk, Lesson, ValidationFinding,
    # operations, events, measurements
    Operation, NptCode, Event, TimeSeries, TimeSeriesPoint, Alert,
    # tools, materials, services, readiness
    ServiceCompany, Service, CatalogItem, InventoryItem, EquipmentUnit, Certification,
    BomRequirement, ReadinessAssessment, ReadinessItem,
    # data fabric & evidence
    RawArtifact, Document, DocumentPage, DocumentRegion, DocumentChunk, ExtractedRecord,
    EvidenceLink, Derivation, IngestionJob,
    # digital twin
    TwinAspect, TwinSnapshot, ChangeRecord,
    # engineering execution
    EngineRun, Recommendation, OffsetCandidate,
    # workflow runtime
    Workflow, WorkflowVersion, WorkflowRun, NodeRun, RunEvent, ApprovalRequest, RunArtifact,
    # optimization & scenarios
    OptimizationRun, CandidateSolution, Scenario, ScenarioChange, ScenarioResult, ImpactAnalysis,
    # AI layer
    LlmCall, AgentRun, ToolCall, PromptTemplate, KnowledgeSource, Conversation, Message,
    MemoryNote, Feedback,
    # registry & platform security/observability/integration
    RegistryItem, RegistryItemVersion, PolicyBinding, AuditLog, SecretRef, IdempotencyKey,
    Trace, Span, MetricPoint, EvaluationSuite, EvaluationCase, EvaluationRun,
    Connector, ConnectorEvent, OutboundMessage, Schedule,
]

__all__ = [
    "ACTION_LEVELS",
    "AGENT_RUN_STATUSES",
    "ALL_MODELS",
    "APPROVAL_KINDS",
    "APPROVAL_STATUSES",
    "ARTIFACT_KINDS",
    "ARTIFACT_STATES",
    "ASPECTS",
    "CAUSE_BASES",
    "CLASSIFICATION_SOURCES",
    "CONNECTOR_PROVIDERS",
    "DATUMS",
    "DOC_STATUSES",
    "DOC_TYPES",
    "EVENT_KINDS",
    "EVENT_SEVERITIES",
    "EVENT_STATUSES",
    "EVIDENCE_KINDS",
    "EXTRACTION_METHODS",
    "INGESTION_JOB_STATUSES",
    "ITEM_CATEGORIES",
    "KNOWLEDGE_SOURCE_KINDS",
    "LLM_OPERATIONS",
    "MESSAGE_ROLES",
    "NODE_RUN_STATUSES",
    "NPT_CATEGORIES",
    "OPERATION_CLASSES",
    "OPERATION_KINDS",
    "OPERATION_PHASES",
    "OPERATION_STATUSES",
    "OPTIMIZATION_PROBLEMS",
    "POLICY_EFFECTS",
    "READINESS_DIMENSIONS",
    "READINESS_STATUSES",
    "RECOMMENDATION_STATUSES",
    "RECORD_TYPES",
    "REGION_KINDS",
    "REGISTRY_KINDS",
    "REGISTRY_STATUSES",
    "RESOURCE_KINDS",
    "RUN_EVENT_TYPES",
    "RUN_STATUSES",
    "SCENARIO_STATUSES",
    "SECTION_KINDS",
    "SERVICE_CATEGORIES",
    "SOURCE_KINDS",
    "SPAN_KINDS",
    "SPAN_OPERATIONS",
    "STATE_KINDS",
    "SURVEY_SOURCES",
    "SYSTEM_ROLES",
    "TOOL_CALL_STATUSES",
    "TRACE_KINDS",
    "TRAJECTORY_KINDS",
    "VALIDATION_STATES",
    "WELLBORE_PURPOSES",
    "WELL_STATUSES",
    "WELL_TYPES",
    "WORKFLOW_STATUSES",
    "AgentRun",
    "Alert",
    "ApiToken",
    "ApprovalRequest",
    "Artifact",
    "ArtifactVersion",
    "AuditLog",
    "Base",
    "BomRequirement",
    "CandidateSolution",
    "CatalogItem",
    "Certification",
    "ChangeRecord",
    "Connector",
    "ConnectorEvent",
    "Conversation",
    "Derivation",
    "Document",
    "DocumentChunk",
    "DocumentPage",
    "DocumentRegion",
    "EngineRun",
    "EquipmentUnit",
    "EvaluationCase",
    "EvaluationRun",
    "EvaluationSuite",
    "Event",
    "EvidenceLink",
    "ExtractedRecord",
    "Feedback",
    "Field",
    "Formation",
    "IdempotencyKey",
    "ImpactAnalysis",
    "IngestionJob",
    "InventoryItem",
    "KnowledgeSource",
    "Lesson",
    "LlmCall",
    "Membership",
    "MemoryNote",
    "Message",
    "MetricPoint",
    "NodeRun",
    "NptCode",
    "OffsetCandidate",
    "Operation",
    "OptimizationRun",
    "Organization",
    "OutboundMessage",
    "PolicyBinding",
    "Project",
    "PromptTemplate",
    "RawArtifact",
    "ReadinessAssessment",
    "ReadinessItem",
    "Recommendation",
    "RegistryItem",
    "RegistryItemVersion",
    "Requirement",
    "Rig",
    "Risk",
    "Role",
    "RunArtifact",
    "RunEvent",
    "Scenario",
    "ScenarioChange",
    "ScenarioResult",
    "Schedule",
    "SecretRef",
    "Service",
    "ServiceCompany",
    "Span",
    "Standard",
    "TimeSeries",
    "TimeSeriesPoint",
    "ToolCall",
    "Trace",
    "Trajectory",
    "TrajectoryStation",
    "TwinAspect",
    "TwinSnapshot",
    "User",
    "ValidationFinding",
    "Well",
    "WellFormationMarker",
    "WellSection",
    "Wellbore",
    "Workflow",
    "WorkflowRun",
    "WorkflowVersion",
]
