"""Engineering engine contract.

An *engineering engine* is a deterministic, versioned, inspectable calculation. It is a
different concept from a tool, a skill, an agent or a workflow node (ADR-0002):

* it has **typed inputs and outputs** whose units are declared in the schema;
* it declares the **context ports** it consumes and produces, which is what lets the
  platform compute change impact and the order in which engines must re-run;
* it declares its **assumptions, limitations and references** so that a result can be
  defended and, where necessary, challenged;
* it is **deterministic**: same inputs (canonical SI) + same version → same outputs hash;
* it never calls an LLM. Numeric engineering answers are not generated by language models.

Engines are invoked identically from the API, a workflow node, an agent tool, an
optimizer or a scheduled job, and every execution is persisted as an ``EngineRun`` with
input/output hashes (reproducibility) and optional evidence links.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field

from drillai.core.errors import EngineInputInvalid
from drillai.units.registry import Dimension

ActionLevel = Literal["L0", "L1", "L2", "L3", "L4", "L5"]

#: Canonical engineering context ports. Engines declare what they consume and produce in
#: terms of these ports; the dependency graph is built from the declarations rather than
#: from hard-coded knowledge of each engine.
PORT_TYPES: dict[str, str] = {
    "well.identity": "Well identity, status, datums and location",
    "well.plan": "Baseline plan / basis of design",
    "wellbore.geometry": "Hole and casing geometry by section",
    "wellbore.section_state": "Current section, depth and progress",
    "wellbore.volumes": "String/annulus capacities, strokes and bottoms-up volumes",
    "trajectory.stations": "Survey stations (plan, actual or revised)",
    "trajectory.summary": "Derived trajectory quantities (TD, max DLS, closure)",
    "formation.markers": "Formation tops/bases with source and confidence",
    "formation.pressures": "Pore pressure, fracture gradient and collapse gradient",
    "mud.properties": "Active mud properties (density, rheology, solids)",
    "bha.assembly": "Bottom-hole assembly composition and dimensions",
    "bit.spec": "Bit specification (type, diameter, nozzles, TFA, ratings)",
    "drillstring.assembly": "Drillstring composition and buoyed weights",
    "rig.limits": "Rig capability limits (pumps, top drive, hookload)",
    "pump.parameters": "Pump output, rate and pressure limits",
    "drilling.parameters": "Operational parameters (WOB, RPM, flow, ROP, torque, SPP)",
    "drilling.performance": "Performance statistics (ROP, MSE, efficiency)",
    "hydraulics.profile": "Pressure losses, ECD and hole-cleaning profile",
    "torque_drag.profile": "Torque, drag and side-force profile",
    "casing.design": "Casing string design and load check results",
    "casing.strings": "Installed casing strings",
    "cement.job": "Cement placement design/results",
    "barriers.state": "Well barrier elements and verification state",
    "completion.design": "Completion string, packers, SCSSV, perforations",
    "intervention.plan": "Intervention / workover plan",
    "integrity.state": "Integrity monitoring state and anomalies",
    "operation.state": "Current, previous and next operation",
    "schedule.state": "Time/depth/cost progress versus plan",
    "npt.statistics": "NPT distribution and Pareto data",
    "offset.statistics": "Offset-well statistics with weights and evidence",
    "offset.candidates": "Scored offset-well candidates",
    "equipment.inventory": "Availability, certification and lead times",
    "services.availability": "Service capability and lead times",
    "readiness.state": "Operational readiness assessment",
    "schematic.model": "Structured well schematic geometry model",
    "risk.register": "Risk register entries relevant to the scope",
    "lessons.learned": "Applicable lessons learned",
    "document.evidence": "Documents and evidence supporting a claim",
    "scenario.result": "Scenario evaluation result",
    "optimization.candidates": "Optimization candidate solutions",
    "recommendation.state": "Recommendations and their decisions",
    "tubular.design": "Tubular design load check results (burst, collapse, tension, triaxial)",
    "well_control.kill_sheet": "Well control kill sheet and pressure schedule",
    "well_control.state": "Well control events, shut-in pressures and kill status",
    "drilling.bit_record": "Bit records, dull grading and run summaries",
    "well.integrity_barriers": "Barrier envelope elements with verification evidence",
    "offset.lessons": "Lessons and hazards compiled from offset wells",
    "schedule.plan": "Planned activity timeline (planned operations and durations)",
    "cost.estimate": "Cost estimates and AFE data",
    "hse.events": "HSE incidents, observations and permits",
    "engine.result": "Engine execution result with assumptions, warnings and violations",
    "twin.state": "Digital well twin state (planned/actual/current/predicted/recommended)",
    "deviation.summary": "Plan-vs-actual deviation summary (lateral/vertical offsets, tolerances)",
    "optimization.problem": "Optimization problem definition (parameters, ranges, objectives)",
    "optimization.frontier": "Pareto frontier and ranked candidate solutions",
    "recommendation.evidence": "Evidence supporting a recommendation",
}


class PortSpec(BaseModel):
    model_config = ConfigDict(frozen=True)
    name: str
    description: str = ""
    required: bool = True

    def validate_known(self) -> None:
        if self.name not in PORT_TYPES:
            raise EngineInputInvalid(f"unknown context port {self.name!r}")


class EngineSpec(BaseModel):
    """Static, inspectable description of an engine."""

    model_config = ConfigDict(frozen=True)
    key: str
    name: str
    version: str
    domain_pack: str
    category: str
    summary: str
    inputs_model: type[BaseModel]
    outputs_model: type[BaseModel]
    consumes: tuple[str, ...] = ()
    produces: tuple[str, ...] = ()
    parameters: dict[str, dict[str, Any]] = Field(default_factory=dict)
    assumptions: tuple[str, ...] = ()
    limitations: tuple[str, ...] = ()
    references: tuple[str, ...] = ()
    tags: tuple[str, ...] = ()
    deterministic: bool = True
    action_level: ActionLevel = "L1"
    requires_well_context: bool = False
    validation_status: str = Field(
        default="verified_against_reference",
        description="verified_against_reference | formula_derived | needs_field_validation",
    )

    def describe(self) -> dict[str, Any]:
        """UI/registry representation, including JSON schemas and declared units."""
        return {
            "key": self.key,
            "name": self.name,
            "version": self.version,
            "domain_pack": self.domain_pack,
            "category": self.category,
            "summary": self.summary,
            "consumes": list(self.consumes),
            "produces": list(self.produces),
            "parameters": self.parameters,
            "assumptions": list(self.assumptions),
            "limitations": list(self.limitations),
            "references": list(self.references),
            "tags": list(self.tags),
            "deterministic": self.deterministic,
            "action_level": self.action_level,
            "requires_well_context": self.requires_well_context,
            "validation_status": self.validation_status,
            "input_schema": self.inputs_model.model_json_schema(),
            "output_schema": self.outputs_model.model_json_schema(),
        }


class ConstraintViolation(BaseModel):
    model_config = ConfigDict(frozen=True)
    name: str
    message: str
    severity: Literal["info", "warning", "error"] = "warning"
    limit: float | None = None
    actual: float | None = None
    unit: str | None = None
    source: str | None = None


class EngineResult(BaseModel):
    """Outcome envelope returned by every engine execution."""

    outputs: BaseModel
    warnings: list[str] = Field(default_factory=list)
    violations: list[ConstraintViolation] = Field(default_factory=list)
    assumptions_applied: list[str] = Field(default_factory=list)
    extra: dict[str, Any] = Field(default_factory=dict)

    @property
    def is_feasible(self) -> bool:
        return not any(v.severity == "error" for v in self.violations)


@runtime_checkable
class Engine(Protocol):
    spec: EngineSpec

    def run(self, inputs: BaseModel) -> EngineResult: ...


class FunctionEngine:
    """Adapter turning a plain function into an engine."""

    def __init__(
        self,
        spec: EngineSpec,
        fn: Callable[[BaseModel], EngineResult],
    ) -> None:
        self.spec = spec
        self._fn = fn

    def run(self, inputs: BaseModel) -> EngineResult:
        if not isinstance(inputs, self.spec.inputs_model):
            raise EngineInputInvalid(
                f"{self.spec.key} expects {self.spec.inputs_model.__name__}, got {type(inputs).__name__}"
            )
        return self._fn(inputs)


def unit_meta(dimension: Dimension | str) -> dict[str, str]:
    value = dimension.value if isinstance(dimension, Dimension) else dimension
    return {"dimension": value}
